# Generated by Django 4.1.4 on 2022-12-18 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(choices=[('name1 last_name1', 'name1'), ('name2 last_name2', 'name2')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.author')),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('time_out', models.DateTimeField(null=True)),
                ('_count', models.IntegerField(db_column='count', default=0)),
                ('article', models.ManyToManyField(through='news.DateText', to='news.text')),
            ],
        ),
        migrations.AddField(
            model_name='datetext',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.datetime'),
        ),
        migrations.AddField(
            model_name='datetext',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.text'),
        ),
    ]
